In [23]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_feature):
        super().__init__()
        self.linear1=nn.Linear(num_feature,3)
        self.relu=nn.ReLU()

        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,feature):
        out=self.linear1(feature)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out

In [24]:
# Create dataset
features=torch.rand(10,5)

# Create model
model=Model(features.shape[1])

# call model forward
model(features)

tensor([[0.5253],
        [0.5215],
        [0.5627],
        [0.5568],
        [0.5229],
        [0.5370],
        [0.5425],
        [0.5167],
        [0.5413],
        [0.5048]], grad_fn=<SigmoidBackward0>)

In [25]:
# show model weight
model.linear1.weight

Parameter containing:
tensor([[-0.3150,  0.1715,  0.1019,  0.0994, -0.1973],
        [ 0.0919,  0.1185,  0.3250, -0.0650,  0.2630],
        [ 0.1984,  0.3846,  0.1945,  0.1010,  0.0918]], requires_grad=True)

In [19]:
model.linear.bias

Parameter containing:
tensor([ 0.1221, -0.0172, -0.3614], requires_grad=True)

In [20]:
!pip install torchinfo


In [26]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [28]:
# Create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_feature):
        super().__init__()
        self.network=nn.Sequential(
        nn.Linear(num_feature,3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())

    def forward(self,feature):
        out=self.network(feature)
        return out