# Tensor Operation on GPU

In [105]:
torch.cuda.is_available()

True

In [108]:
device=torch.device("cuda")
device

device(type='cuda')

In [109]:
# Creating a new Tensor on gpu
x=torch.rand(2,3,device=device)
x

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [114]:
# Moving an existing tensor on gpu
z=a.to(device)

In [115]:
z+3

tensor([[13.0000,  3.3079,  3.6269],
        [ 3.8277,  3.6594,  3.0887]], device='cuda:0')

In [117]:
import time
# define the size of matrix
size=10000  # large size for performance comparison

# create random matrix on cpu
matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

# measure time on cpu
start_time=time.time()
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time()-start_time

print("Time taken by cpu:",cpu_time)

# create random matrix on gpu
matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

# measure time on gpu
start_time=time.time()
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
gpu_time=time.time()-start_time

print("Time taken by gpu:",gpu_time)

print("Speedup factor (cpu_time/gpu_time):",cpu_time/gpu_time)

























Time taken by cpu: 16.577577114105225
Time taken by gpu: 0.00029468536376953125
Speedup factor (cpu_time/gpu_time): 56255.17637540453


# Reshape Tensors

In [118]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [119]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [120]:
# flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [121]:
b=torch.rand(2,3,4)
b

tensor([[[0.4067, 0.9891, 0.1025, 0.9936],
         [0.3642, 0.8499, 0.3817, 0.2436],
         [0.1008, 0.1176, 0.3651, 0.4549]],

        [[0.8776, 0.3721, 0.7827, 0.4926],
         [0.7323, 0.4682, 0.4369, 0.3151],
         [0.6987, 0.7903, 0.5187, 0.7766]]])

In [123]:
# permute
b.permute(2,1,0).shape

torch.Size([4, 3, 2])

In [129]:
# Unsqueeze
#image size
c=torch.rand(226,226,3)
c.unsqueeze(2).shape


torch.Size([226, 226, 1, 3])

In [135]:
# Squeeze
d=torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

# Numpy And Tensorflow

In [136]:
import numpy as np


In [137]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [138]:
b=a.numpy()

In [139]:
b

array([1, 2, 3])

In [141]:
type(b)

numpy.ndarray

In [142]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [144]:
d=torch.from_numpy(c)

In [145]:
d

tensor([1, 2, 3])

In [146]:
type(d)

torch.Tensor

In [4]:
import torch
print(torch.__version__)

2.11.0+cu128


In [5]:
if torch.cuda.is_available():
    print("GPU is available")
    print(torch.cuda.get_device_name(0))
else:
    print("GPU is not available. using CPU")


GPU is available
Tesla T4


# Creating Tensors

In [9]:
# using empty fuction is used to allocate the memory
a=torch.empty(2,3)

In [10]:
# check type
type(a)

torch.Tensor

In [11]:
# using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [12]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
# using rand
torch.rand(2,3)

tensor([[0.9399, 0.1166, 0.4337],
        [0.4207, 0.6176, 0.2522]])

In [14]:
# using manual_seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [15]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [16]:
# using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# others ways
# arrage
print("using arrage ->",torch.arange(1,10,2))
# linspace
print("using linspace ->",torch.linspace(0,10,10))

# using eye
print("using eye ->",torch.eye(3))

# using full
print("using full ->",torch.full((3,3),5))


using arrage -> tensor([1, 3, 5, 7, 9])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


# Tensors Shape

In [20]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [21]:
torch.empty_like(x)

tensor([[     1102915360,      1101207568, 137494788046848],
        [             97,      1102903536,      1103014928]])

In [22]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [23]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [29]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

# Tensor Data Types

In [25]:
# find data types
x.dtype

torch.int64

In [26]:
# assign datatype
torch.tensor([[1.0,2.0,3.0]],dtype=torch.int32)

tensor([[1, 2, 3]], dtype=torch.int32)

In [27]:
torch.tensor([[1,2,3]],dtype=torch.float32)

tensor([[1., 2., 3.]])

In [28]:
# Change datatypes
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

 **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


# Mathematical Operations

## 1.Scalar Operation

In [31]:
x=torch.rand(2,3)
x

tensor([[0.2239, 0.3023, 0.1784],
        [0.8238, 0.5557, 0.9770]])

In [32]:
# addition
x + 2
# substraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x**2

tensor([[0.0501, 0.0914, 0.0318],
        [0.6787, 0.3089, 0.9546]])

## 2. Element wise operation

In [33]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4440, 0.9478, 0.7445],
        [0.4892, 0.2426, 0.7003]])
tensor([[0.5277, 0.2472, 0.7909],
        [0.4235, 0.0169, 0.2209]])


In [34]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4440, 0.2063, 0.7445],
        [0.0657, 0.0060, 0.0377]])

In [35]:
c = torch.tensor([1, -2, 3, -4])

In [36]:
# Abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [37]:
# Negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [38]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [39]:
# round
torch.round(d)

tensor([2., 2., 4., 4.])

In [40]:
# ceil
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [41]:
# floor
torch.floor(d)

tensor([1., 2., 3., 4.])

In [42]:
# clamp
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

## 3. Reduction operation

In [43]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[3., 9., 4.],
        [0., 5., 7.]])

In [45]:
# sum
torch.sum(e)

# sum along columns
torch.sum(e, dim=0)

# sum along rows
torch.sum(e, dim=1)

tensor([16., 12.])

In [46]:
# mean
torch.mean(e)

# mean along columns
torch.mean(e, dim=0)

# mean along rows
torch.mean(e, dim=1)

tensor([5.3333, 4.0000])

In [47]:
# Median
torch.median(e)

# Median along columns
torch.median(e, dim=0)

# Median along rows
torch.median(e, dim=1)

torch.return_types.median(
values=tensor([4., 5.]),
indices=tensor([2, 1]))

In [48]:
# max and min
torch.max(e)
torch.min(e)

tensor(0.)

In [ ]:
# Product
torch.prod(e)
torch.prod(e, dim=0)
torch.prod(e, dim=1)

In [49]:
# Standard Deviation
torch.std(e)
torch.std(e, dim=0)
torch.std(e, dim=1)

tensor([3.2146, 3.6056])

In [50]:
# variance
torch.var(e)
torch.var(e, dim=0)
torch.var(e, dim=1)

tensor([10.3333, 13.0000])

In [51]:
# argmax
torch.argmax(e)
torch.argmax(e, dim=0)
torch.argmax(e, dim=1)

tensor([1, 2])

In [52]:
# argmin
torch.argmin(e)
torch.argmin(e, dim=0)
torch.argmin(e, dim=1)

tensor([0, 0])

# 4. Matrix Operations

In [53]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[5, 9, 9],
        [7, 5, 9]])
tensor([[8, 9],
        [7, 9],
        [2, 6]])


In [54]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[121, 180],
        [109, 162]])

In [56]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)


tensor(11)

In [57]:
# transpose
torch.transpose(f, 0, 1)

tensor([[5, 7],
        [9, 5],
        [9, 9]])

In [58]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[7., 7., 8.],
        [3., 6., 1.],
        [5., 5., 0.]])

In [59]:
# determinant
torch.det(h)

tensor(-120.)

In [60]:
# inverse
torch.inverse(h)

tensor([[ 4.1667e-02, -3.3333e-01,  3.4167e-01],
        [-4.1667e-02,  3.3333e-01, -1.4167e-01],
        [ 1.2500e-01, -6.9539e-09, -1.7500e-01]])

## 5. Comparison operations

In [61]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[4, 3, 8],
        [8, 3, 3]])
tensor([[5, 0, 6],
        [4, 0, 8]])


In [62]:
# greater than
i > j
# less than
i < j
# equal to
i == j
# not equal to
i != j
# greater than equal to
i >= j

# less than equal to
i<= j


tensor([[ True, False, False],
        [False, False,  True]])

## 6. Special functions

In [63]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[4., 7., 2.],
        [3., 8., 5.]])

In [64]:
# log
torch.log(k)

tensor([[1.3863, 1.9459, 0.6931],
        [1.0986, 2.0794, 1.6094]])

In [65]:
# exp
torch.exp(k)

tensor([[  54.5981, 1096.6332,    7.3891],
        [  20.0855, 2980.9580,  148.4132]])

In [66]:
# sqrt
torch.sqrt(k)

tensor([[2.0000, 2.6458, 1.4142],
        [1.7321, 2.8284, 2.2361]])

In [67]:
# sigmoid
torch.sigmoid(k)

tensor([[0.9820, 0.9991, 0.8808],
        [0.9526, 0.9997, 0.9933]])

In [68]:
# softmax
torch.softmax(k, dim=0)

tensor([[0.7311, 0.2689, 0.0474],
        [0.2689, 0.7311, 0.9526]])

In [69]:
# relu
torch.relu(k)

tensor([[4., 7., 2.],
        [3., 8., 5.]])

## Inplace Operations

In [77]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.0497, 0.1780, 0.3011],
        [0.1893, 0.9186, 0.2131]])
tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])


In [80]:
m.add_(n)

tensor([[0.4454, 0.7796, 0.7245],
        [0.7117, 1.3361, 0.2472]])

In [81]:
m

tensor([[0.4454, 0.7796, 0.7245],
        [0.7117, 1.3361, 0.2472]])

In [82]:
n

tensor([[0.3957, 0.6017, 0.4234],
        [0.5224, 0.4175, 0.0340]])

In [83]:
torch.relu(m)

tensor([[0.4454, 0.7796, 0.7245],
        [0.7117, 1.3361, 0.2472]])

In [84]:
m.relu_()

tensor([[0.4454, 0.7796, 0.7245],
        [0.7117, 1.3361, 0.2472]])

In [85]:
m

tensor([[0.4454, 0.7796, 0.7245],
        [0.7117, 1.3361, 0.2472]])

## Copying a Tensor

In [86]:
a = torch.rand(2,3)
a

tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [87]:
b = a

In [88]:
b

tensor([[0.9157, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [89]:
a[0][0] = 0

In [90]:
a

tensor([[0.0000, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [91]:
b

tensor([[0.0000, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [92]:
id(a)

137497296051312

In [93]:
id(b)

137497296051312

In [94]:
id(a)==id(b)

True

In [95]:
b=a.clone()

In [96]:
a

tensor([[0.0000, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [97]:
b

tensor([[0.0000, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [99]:
a[0][0]=10


In [100]:
a

tensor([[10.0000,  0.3079,  0.6269],
        [ 0.8277,  0.6594,  0.0887]])

In [101]:
b

tensor([[0.0000, 0.3079, 0.6269],
        [0.8277, 0.6594, 0.0887]])

In [102]:
id(b)

137497296056832

In [103]:
id(a)

137497296051312

In [104]:
id(a)==id(b)

False